# Generated by Django 5.1.1 on 2024-09-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Temperature', 'Temperature'), ('Humidity', 'Humidity'), ('Counter', 'Counter'), ('Luminosity', 'Luminosity')], max_length=50)),
                ('mac_address', models.CharField(max_length=20, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('location', models.CharField(max_length=100)),
                ('responsible', models.CharField(max_length=100)),
                ('measurement_unit', models.CharField(blank=True, max_length=20, null=True)),
                ('operational_status', models.BooleanField(default=True)),
                ('observation', models.TextField(blank=True)),
            ],
        ),
    ]
