# Generated by Django 5.1.1 on 2024-10-03 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_smart', '0002_alter_sensor_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor',
            old_name='location',
            new_name='localizacao',
        ),
        migrations.RenameField(
            model_name='sensor',
            old_name='observation',
            new_name='observacao',
        ),
        migrations.RenameField(
            model_name='sensor',
            old_name='responsible',
            new_name='responsavel',
        ),
        migrations.RenameField(
            model_name='sensor',
            old_name='operational_status',
            new_name='status_operacional',
        ),
        migrations.RenameField(
            model_name='sensor',
            old_name='type',
            new_name='tipo',
        ),
        migrations.RenameField(
            model_name='sensor',
            old_name='measurement_unit',
            new_name='unidade_medida',
        ),
    ]
