# Generated by Django 5.1.1 on 2024-10-04 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_smart', '0005_alter_luminosidadedata_timestamp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contadordata',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='umidadedata',
            name='timestamp',
        ),
    ]
